package com.sixCoders.suse.model;

import java.math.BigDecimal;

public class Cart {

    private Integer cartId;
    
    private Integer cartNum;

    private BigDecimal totalPrice;
    
    private Integer pId;

 
    private Integer userId;
    
    private Shop shop;

 
 


	public Integer getCartId() {
        return cartId;
    }


    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }



    public Integer getCartNum() {
		return cartNum;
	}


	public void setCartNum(Integer cartNum) {
		this.cartNum = cartNum;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.total_price
     *
     * @return the value of cart.total_price
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.total_price
     *
     * @param totalPrice the value for cart.total_price
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.p_id
     *
     * @return the value of cart.p_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.p_id
     *
     * @param pId the value for cart.p_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


	public Shop getShop() {
		return shop;
	}


	public void setShop(Shop shop) {
		this.shop = shop;
	}


	@Override
	public String toString() {
		return "Cart [cartId=" + cartId + ", cartNum=" + cartNum + ", totalPrice=" + totalPrice + ", pId=" + pId
				+ ", userId=" + userId + ", shop=" + shop + "]";
	}
	
}