package com.sixCoders.suse.model;

public class Seller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String sNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_password
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String sPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.s_address
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String sAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.flag
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_id
     *
     * @return the value of seller.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_id
     *
     * @param sId the value for seller.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_num
     *
     * @return the value of seller.s_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getsNum() {
        return sNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_num
     *
     * @param sNum the value for seller.s_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsNum(String sNum) {
        this.sNum = sNum == null ? null : sNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_name
     *
     * @return the value of seller.s_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_name
     *
     * @param sName the value for seller.s_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_password
     *
     * @return the value of seller.s_password
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getsPassword() {
        return sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_password
     *
     * @param sPassword the value for seller.s_password
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsPassword(String sPassword) {
        this.sPassword = sPassword == null ? null : sPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.s_address
     *
     * @return the value of seller.s_address
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.s_address
     *
     * @param sAddress the value for seller.s_address
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.flag
     *
     * @return the value of seller.flag
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.flag
     *
     * @param flag the value for seller.flag
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}