package com.sixCoders.suse.model;

import java.math.BigDecimal;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer pId;
private String path;


    public String getPath() {
	return path;
}

public void setPath(String path) {
	this.path = path;
}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_content
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String pContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer pNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_price
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private BigDecimal pPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_state
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer pState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_family
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String pFamily;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_genus
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String pGenus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.p_picture
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private String pPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    private Integer sId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_id
     *
     * @return the value of shop.p_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_id
     *
     * @param pId the value for shop.p_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_name
     *
     * @return the value of shop.p_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_name
     *
     * @param pName the value for shop.p_name
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_content
     *
     * @return the value of shop.p_content
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getpContent() {
        return pContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_content
     *
     * @param pContent the value for shop.p_content
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpContent(String pContent) {
        this.pContent = pContent == null ? null : pContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_num
     *
     * @return the value of shop.p_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_num
     *
     * @param pNum the value for shop.p_num
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpNum(Integer pNum) {
        this.pNum = pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_price
     *
     * @return the value of shop.p_price
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public BigDecimal getpPrice() {
        return pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_price
     *
     * @param pPrice the value for shop.p_price
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpPrice(BigDecimal pPrice) {
        this.pPrice = pPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_state
     *
     * @return the value of shop.p_state
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getpState() {
        return pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_state
     *
     * @param pState the value for shop.p_state
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpState(Integer pState) {
        this.pState = pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_family
     *
     * @return the value of shop.p_family
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getpFamily() {
        return pFamily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_family
     *
     * @param pFamily the value for shop.p_family
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpFamily(String pFamily) {
        this.pFamily = pFamily == null ? null : pFamily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_genus
     *
     * @return the value of shop.p_genus
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getpGenus() {
        return pGenus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_genus
     *
     * @param pGenus the value for shop.p_genus
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpGenus(String pGenus) {
        this.pGenus = pGenus == null ? null : pGenus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.p_picture
     *
     * @return the value of shop.p_picture
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public String getpPicture() {
        return pPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.p_picture
     *
     * @param pPicture the value for shop.p_picture
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setpPicture(String pPicture) {
        this.pPicture = pPicture == null ? null : pPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.s_id
     *
     * @return the value of shop.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.s_id
     *
     * @param sId the value for shop.s_id
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }
}