package com.sixCoders.suse.dao;

import com.sixCoders.suse.model.Cart;
import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int deleteByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    Cart selectByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    List<Cart> selectAll(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int updateByPrimaryKey(Cart record);
    
    void deleteAll(int UserId);
}