package com.sixCoders.suse.dao;

import com.sixCoders.suse.model.Seller;
import java.util.List;

public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    Seller selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    List<Seller> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int updateByPrimaryKey(Seller record);
}