package com.sixCoders.suse.dao;

import com.sixCoders.suse.model.Shop;
import java.util.List;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    Shop selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    List<Shop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jul 05 20:53:32 CST 2018
     */
    int updateByPrimaryKey(Shop record);
    /**
     * 
     * 根据植物科类查询
     */
    List<Shop> selectByCondition(String condition);
    /**
     * 
     * 根据商品名称查询
     */
    List<Shop> selectByProductName(String productName);
    
}